name = "cf_ai_armonia"
main = "api/index.js"
compatibility_date = "2024-10-24"

[ai]
binding = "AI" 

[durable_objects]
bindings = [
  { name = "MEMORY", class_name = "MemoryDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MemoryDO"]
